[package]
name = "png2ascii"
authors = ["Ethan Zhang <ezsland05@gmail.com>"]
categories = ["command-line-utilities", "graphics"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
